# -*- coding: utf-8 -*-

"""
/***************************************************************************
 RasterNodata
                                 A QGIS plugin
 Set, update, remove nodata value for raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-01-19
        copyright            : (C) 2019 by suricactus
        email                : suricactus@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'suricactus'
__date__ = '2019-01-19'
__copyright__ = '(C) 2019 by suricactus'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import inspect

from PyQt5.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterBand,
                       QgsProcessingParameterRasterDestination)

from processing.algs.gdal.GdalUtils import GdalUtils

DATATYPE_BYTE = 1
DATATYPE_UINT16 = 2
DATATYPE_UINT32 = 4


class RasterNodataAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    BANDS = 'BANDS'
    NODATA = 'NODATA'
    FILLDATA = 'FILLDATA'
    NODATA_SKIP = 'NODATA_SKIP'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input layer'),
            )
        )

        self.addParameter(
            QgsProcessingParameterBand(
                self.BANDS,
                self.tr('Band number'),
                # defaultValue=1,
                parentLayerParameterName=self.INPUT,
                allowMultiple=True
            )
        )


        self.addParameter(
            QgsProcessingParameterNumber(
                self.NODATA,
                self.tr('Nodata value (optional)'),
                type=QgsProcessingParameterNumber.Double,
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.NODATA_SKIP,
                self.tr('Nodata value as same as the source raster (ignores the option above)'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.FILLDATA,
                self.tr('Fill values'),
                type=QgsProcessingParameterNumber.Double
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        source = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        # ogrLayer, layerName = self.getOgrCompatibleSource(self.INPUT, parameters, context, feedback, executing)

        if source is None:
            raise QgsProcessingException(self.invalidRasterError(parameters, self.INPUT))

        dst_nodata_skip = self.parameterAsBool(parameters, self.NODATA_SKIP, context)
        dst_nodata_value = self.parameterAsDouble(parameters, self.NODATA, context)
        filldata_value = self.parameterAsDouble(parameters, self.FILLDATA, context)
        out = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)
        out_tmp = out.replace('OUTPUT', 'OUTPUT1')

        bands = []
        src_nodata_values = []
        dst_nodata_values = []
        filldata_values = []

        for band in range(source.bandCount()):
            band += 1
            src_nodata_value = source.dataProvider().sourceNoDataValue(band)

            if dst_nodata_skip:
                dst_nodata_value = src_nodata_value

            if dst_nodata_value == filldata_value:
                raise Exception('The new nodata value and the fill nodata are equal. Should be different.')

            if source.dataProvider().dataType(band) in (DATATYPE_BYTE, DATATYPE_UINT16, DATATYPE_UINT32):
                if dst_nodata_value < 0:
                    raise Exception('Nodata value cannot be less than 0 in layer with this data type')

                if filldata_value < 0:
                    raise Exception('Fill value cannot be less than 0 in layer with this data type')

            if dst_nodata_value is None:
                dst_nodata_value = 'none'

            bands.append(band)
            src_nodata_values.append(src_nodata_value)
            dst_nodata_values.append(dst_nodata_value)
            filldata_values.append(filldata_value)

        warp_arguments = []
        translate_arguments = []

        warp_arguments.append('-srcnodata')
        warp_arguments.append('"{}"'.format(' '.join(map(str, src_nodata_values))))
        warp_arguments.append('-dstnodata')
        warp_arguments.append('"{}"'.format(' '.join(map(str, filldata_values))))
        warp_arguments.append(source.source())
        warp_arguments.append(out_tmp)


        translate_arguments.append('-a_nodata')
        translate_arguments.append('"{}"'.format(' '.join(map(str, dst_nodata_values))))
        translate_arguments.append(out_tmp)
        translate_arguments.append(out)

        commands = ['gdalwarp', GdalUtils.escapeAndJoin(warp_arguments)]

        GdalUtils.runGdal(commands, feedback)

        commands = ['gdal_translate', GdalUtils.escapeAndJoin(translate_arguments)]

        GdalUtils.runGdal(commands, feedback)

        results = {}

        for o in self.outputDefinitions():
            if o.name() in parameters:
                results[o.name()] = parameters[o.name()]

        return results

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Raster nodata'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'GDAL'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RasterNodataAlgorithm()
