# -*- coding: utf-8 -*-

"""
/***************************************************************************
 RasterNodata
                                 A QGIS plugin
 Set, update, remove nodata value for raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-01-19
        copyright            : (C) 2019 by suricactus
        email                : suricactus@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'suricactus'
__date__ = '2019-01-19'
__copyright__ = '(C) 2019 by suricactus'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .RasterNodataProvider import RasterNodataProvider

class RasterNodataPlugin(object):

    def __init__(self):
        self.provider = RasterNodataProvider()

    def initGui(self):
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
